package com.i2icellcelly.DGW.Business;

import org.json.simple.JSONObject;

/**
 * Routes the traffic that is generated by the simulator to the OCS. The messages that are sent by the
 * simulator are parsed, reformatted, and finally the Partition Keys to be used for faster VoltDB queries
 * are added to the final message that will be sent to the OCS.
 */
public interface ITrafficService {
    void generateTraffic(JSONObject message);
}
